version: '2'
services:
    comicbooks-app:
        image: comicbooks
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://comicbooks-postgresql:5432/comicbooks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    comicbooks-postgresql:
        extends:
            file: postgresql.yml
            service: comicbooks-postgresql
